[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "numpy>=1.17.0",
    "cmake>=3.18.0; platform_system!='Windows'",  # Optional, if you decide to use scikit-build
]
build-backend = "setuptools.build_meta"